apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset-multi
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/<your-username>/nginx-argocd.git
      revision: main
      directories:
        - path: k8s
        - path: k8s-2

  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/venkatasai987/argo-app.git
        targetRevision: main
        path: k8s
        helm:
          parameters:
            - name: image.tag
              value: '{{imageTag}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
